#!/bin/bash

USER=`whoami`

if [ "$USER" != "gpadmin" ]; then
        echo "ERROR: Database must be setup as user gpadmin"
        exit 1
fi

echo "Running ANALYZE... this may take a while!"
time psql -d exploitatie -c "ANALYZE;"
echo "ANALYZE Finished!"