#!/bin/bash

echo "Fixing libs..."

if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "Run as sudo / root"
    exit 1
fi
cd "/usr/local/greenplum-db"

# libraries shipped with Greenplum SNE
gplibs="$(find -maxdepth 1 -type f | cut -f 2 -d /)"

# libraries with same abi installed via dpkg
deblibs="$(dpkg -S $gplibs 2> /dev/null | cut -f 2  -d ' ')"

# we remove the greenplum one to avoid "no version information available" errors
for lib in $deblibs; do
  ver=$(basename $lib)
  rm -fv $ver
  while [ $ver = ${ver#.so} ]&&[ $ver != ${ver%.so*} ]; do
      ver=${ver%.*}
      rm -fv $ver
  done
done

echo "Done"
echo ""
echo "All finished!"