#!/bin/bash

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "ERROR: Run as sudo / root!"
    exit 1
fi

# find pid file
if [ ! -f /mnt/voltdb/.pid ]; then
    echo "ERROR: unable to find .pid file of running VoltDB"
    exit 1
fi

PID=$(cat /mnt/voltdb/.pid)

echo "Killing VoltDB process ($PID)..."

kill -9 "$PID"

echo "Killed!"
