#!/bin/bash

# Prepares a single node for Vertica, The Analytical Database.
# This script has been tested with Vertica 6.0.1 Community Edition and Vertica 6.1.0 Enterprise Edition
#
# Created by Daniël Knippers for Topicus I&I as part of an internship assignment.
# The internship started on 2012-09-03 and ended on 2012-12-07

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "Run as sudo / root"
    exit 1
fi

MAX_OPEN_FILES=65536
MAX_FSIZE='unlimited'
IP=`ifconfig | grep -zoP '(?s)eth0.*?inet addr:.*?\s' | grep -oP '(\d{1,3}\.){3}\d{1,3}'`
HOSTNAME=`/bin/hostname`
COLS=80 # The built-in variable $COLUMNS does not work, so just use width 80

# Prints a description, runs command(s) and prints a confirmation
# Note it cannot actually handle failures. Consider that a TODO =)
run() {
    echo -ne "$2"
    eval $1
    let "space = $COLS - ${#2}"
    printf "%${space}s\n" "[ OK ]"
}

# Installs whatever package is given as argument, if it is not installed yet
install() {
    [ -z "`dpkg --get-selections | grep \"^$1\s\+install$\"`" ] && apt-get -y install $1 > /dev/null
}

# Vertica searches for 4., 5. or 6. in /etc/debian_version to recognize Debian, so add it if required
debian_version() {
    [ -z `cat /etc/debian_version | grep ^[456]\\\.` ] && echo "6." >> /etc/debian_version
}

# Install NTP, add Dutch servers to config, restart service
setup_ntp() {
    install 'ntp'
    sed -i 's/\(server\s\+\)\([0-9]\+\)\.ubuntu\.pool\.ntp\.org/\1\2\.nl\.pool\.ntp\.org/g' /etc/ntp.conf
    service ntp restart > /dev/null
}

# Install the SSH package if it's not installed
# Note this is just a convenience package which includes
# openssh-client and openssh-server
setup_ssh() {
    install 'ssh'
}

# Install sysstat if it's not installed (Vertica installer recommended this package)
setup_sysstat() {
    install 'sysstat'
}
# Install pstack if it's not installed (Vertica installer recommended this package)
setup_pstack()  {
    install 'pstack'
}

# Add this node's IP address and hostname to /etc/hosts
# And remove 127.0.1.1, Vertica would use it instead of the actual IP for the host
modify_hosts() {
    sed -i 's/127\.0\.1\.1\s\+\w\+//g' /etc/hosts
    [ -z "`cat /etc/hosts | grep \"$IP\\s\+$HOSTNAME$\"`" ] && echo "$IP $HOSTNAME" >> /etc/hosts

    # Remove empty lines from /etc/hosts
    perl -i -p -e 's/^\n$//' /etc/hosts
}

# Add correct maximum open files and maximum file size limits to limits.conf
modify_limits() {
    limits=/etc/security/limits.conf
    domains=( "root" "*" )
    types=( "hard" "soft" )

    for i in ${!domains[@]}
    do
        for j in ${!types[@]}
        do
            d=${domains[$i]}
            t=${types[$j]}
            [ `ulimit -n` -lt $MAX_OPEN_FILES ] && echo "$d $t nofile $MAX_OPEN_FILES" >> $limits
            [ `ulimit -f` != $MAX_FSIZE ] && echo "$d $t fsize $MAX_FSIZE" >> $limits
        done
    done
}

# Set the $TZ variable to whatever is in /etc/timezone
# Note you have to log out before this works, so Vertica still whines about it
# during installation. Not sure when Vertica uses this, but I guess they do at some point
set_timezone() {
    TZ=`cat /etc/timezone`
    [ -z `cat ~/.bashrc | grep '^TZ='` ] && echo TZ=\'$TZ\' >> ~/.bashrc
}

# Adds /opt/vertica/bin to the user PATH. Primarly useful for executing admintools / vsql
update_path() {
    [ -z `cat ~/.bashrc | grep '^PATH=$PATH:/opt/vertica/bin'` ] && echo 'PATH=$PATH:/opt/vertica/bin' >> ~/.bashrc
}

# Removes the ~/.ssh directory which contains public keys of other nodes.
# Installing Vertica will re-create this directory anyway, and it will not install
# properly when the directory already exists with keys in there
clean_ssh_dir() {
    [ -d ~/.ssh ] && rm -rf ~/.ssh
}

run setup_ntp      'Setting up NTP'
run setup_ssh      'Setting up SSH'
run setup_sysstat  'Setting up sysstat'
run setup_pstack   'Setting up pstack'
run debian_version 'Modifying /etc/debian_version'
run modify_hosts   'Modifying /etc/hosts'
run modify_limits  'Modifying /etc/security/limits.conf'
run set_timezone   'Setting $TZ variable to /etc/timezone'
run update_path    'Adding /opt/vertica/bin to PATH'
run clean_ssh_dir  'Cleaning existing configuration in ~/.ssh directory'