#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "ERROR: Run as sudo / root"
    exit 1
fi

MASTER_HOST=$1
MASTER_PORT=$2
MASTER_DB="master"
INSTANCE_DIR="$3"

if [ "$INSTANCE_DIR" == "" ]; then
    echo "ERROR: must specify base directory for instances as 3rd argument!"
    exit 1
fi

if [ ! -d "$INSTANCE_DIR" ]; then
    echo "ERROR: invalid instance base directory specified!"
    exit 1
fi

echo "user=monetdb" >> ".monetdb"
echo "password=monetdb" >> ".monetdb"

HOSTNAME=`hostname`
echo "Deleting instances on $HOSTNAME..."
for subDir in $INSTANCE_DIR/instance-* ; do
    if [ -d $subDir ]; then
        # get port of instance
        PORT=`monetdbd get "port" "$subDir"`
        PORT=`echo $PORT | awk -F '[ ,]+' '{print $4}' -`

        # stop all databases
        echo "  Stopping all databases on instance $subDir on host $HOSTNAME..."
        monetdb -p "$PORT" stop -a
        echo "  Done"

        # stopping instance
        echo "  Stopping instance..."
        monetdbd stop "$subDir"
        echo "  Done"

        # delete actual instance directory
        echo "  Deleting instance directory..."
        rm -rf "$subDir"
        echo "  Done"

        # notify master about deleted instance
        echo "  Notifying master database..."
        echo "DELETE FROM instance WHERE instance_host = '$HOSTNAME' AND instance_port = '$PORT';" | mclient -h "$MASTER_HOST" -p "$MASTER_PORT" -d "$MASTER_DB" -
        echo "  Done"
    fi
done

rm ".monetdb"

echo "All instances deleted"