#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "ERROR: Run as sudo / root"
    exit 1
fi

# validate config file
CONFIG_FILE=$1
if [ "$CONFIG_FILE" == "" -o ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: 1st argument must be a valid config file!"
    exit 1
fi

# read config file
source "$CONFIG_FILE"

if [ -f "$MASTER_DIR/merovingian.pid" ]; then
    echo "Stopping master database..."
    monetdb -p "$MASTER_PORT" stop -a
    echo "Done"

    echo "Stopping master instance..."
    monetdbd stop "$MASTER_DIR"
    echo "Done"
else
    echo "Master instance is not running!"
fi

echo "Deleting master directory..."
rm -rf "$MASTER_DIR"
echo "Done"

echo "Master has been stopped and deleted"
echo "Finished!"