#!/bin/bash

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "Run as sudo / root"
    exit 1
fi

set -x

# make sure APT-GET is up-to-date
apt-get update && apt-get upgrade -y

# install Java
apt-get install openjdk-7-jdk -y

# install unzip
apt-get install unzip -y

# install ant
apt-get install ant -y

# install PHP5-CLI
apt-get install php5-cli y

# create benchmarking structure
mkdir -p /benchmarking/

cd /benchmarking/

# download tools and unzip
wget -qO- -O tmp.zip https://github.com/topicus-ini/benchmarking-dennis/archive/master.zip && unzip tmp.zip && rm tmp.zip
mv benchmarking-dennis-master/* .
rm -rf benchmarking-dennis-master/

ln -s java/build tools

# build tools and make executable
cd java
ant build create-scripts
cd /benchmarking/
chmod -R +x .

# add scripts to PATH
echo "export PATH=$PATH:/benchmarking/tools:/benchmarking/tools/manage-cluster" >> ~/.profile
source ~/.profile

printf "\n\nAll OK! Instance is fully setup!\n\n"