#!/bin/bash

echo "===== MonetDB Delete MasterDB Script ====="
echo "This script is used to stop and delete the master database"
echo ""

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# run actual master script
"$SCRIPT_DIR/lib/delete_master" "$1"