#!/bin/bash

echo "===== MonetDB Delete Instances Script ====="
echo "This script is used to stop and delete node instances"
echo ""

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "ERROR: Run as sudo / root"
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# run actual delete instances script
"$SCRIPT_DIR/lib/delete_instances" "$1" $2 "$3"

echo "All finished!"