#!/bin/bash

echo "===== MonetDB Start MasterDB Script ====="
echo "This script is used to setup and start the master database"
echo ""

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "ERROR: Run as sudo / root"
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# run actual master script
"$SCRIPT_DIR/lib/start_master" "$1"

