#!/bin/bash

echo "===== MonetDB Start Instances Script ====="
echo "This script is used to setup and start node instances"
echo ""

# The script needs admin rights
if [ `/usr/bin/id -u` -ne 0 ]; then
    echo "ERROR: Run as sudo / root"
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# run actual start instances script
"$SCRIPT_DIR/lib/start_instances" "$1" $2 $3 "$4" $5 "$6"


echo "All finished!"